# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ksenia Lukin
title: Data Scientiest & Data Analyst
email: kseniia.lukin@gmail.com
website: www.github.com/kslukin

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  kslukin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kspks
linkedin_username: kslukin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/created_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey, Iâ€™m Ksenia! Iâ€™m into data ğŸ“Š â€“ figuring out how things work behind the scenes and finding ways to make them better. I enjoy working with data to solve real-world problems ğŸ’¡ and constantly challenge myself to try new tools and methods ğŸ› ï¸. 
  When Iâ€™m not coding ğŸ’», youâ€™ll probably find me thinking about ways to make complicated things easier to understand ğŸ§  or diving deep into a new problem to crack it.

  I am most skilled in: <mark>Math</mark>,<mark>DS & MLğŸ¤–</mark>,  <mark>Python, SQL, PySpark</mark>,  <mark>Data Visualization & Reporting</mark> and <mark>Eating Pizza ğŸ•</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
    ##    title: Super awesome project
    ##    link: github.com/sproogen
        # link_text: Project Website
    ##    additional_links:
    ##      - title:  sproogen/modern-resume-theme
    ##        icon: fab fa-github
    ##        url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
   ##     quote: >
   ##       This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
   ##     description: | # this will include new lines to allow paragraphs
  ##      I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ğŸ‡©ğŸ‡ª Siemens Healthineers
        link: siemens-healthineers.com
        # link_text: boringcompany.com
        sub_title: Data Scientist  in Projects & Digital - Diagnostic Imaging Finance (Working Student)
        caption: August 2022 - December 2023
        quote: >
            "A global leader in medical technology, driving innovation in diagnostics and healthcare solutions worldwide."
       #    Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          In this role, I worked on real-world challengesâ€”from forecasting medical equipment demand with time series models to building an internal ChatGPT-like tool for financial reporting. What truly excited me was the chance to explore massive datasets, experiment with new methods, and turn complexity into clarityâ€”both through visualizations and by making technical ideas accessible to non-technical teams. Iâ€™ve always had a passion for math and statistics, even before they were trendy, and I love when that passion turns into practical impact.
          
          ğŸ“Œ Hereâ€™s an overview of my contributions:
          - Took **sparse financial data** and turned it into something meaningful by leveraging **DataBricks** and **PySpark** for powerful modeling and harmonization.
          - Developed and fine-tuned **time series forecasting models** (think **ARIMA** and **DeepAR**) to boost revenue predictions, helping the company optimize planning and decision-making.
          - Played a key role in integrating **internal data sources with GPT models**, creating smooth workflows using **LangChain** to supercharge internal processes.
          - Explored the potential of **large language models (LLMs)** to automate **internal financial processes**, significantly improving efficiency across the board.
 
          Technologies & Tools:  
          - **Azure DataBricks**, **PySpark**, **NumPy**, **pandas**, **NLP**, **DeepAR**, **ARIMA**, **scikit-learn**, **TensorFlow**, **Jupyter Notebooks**, **LangChain**, **Matplotlib**.

          
      #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ğŸ“ Friedrichâ€“Alexander University Erlangenâ€“NÃ¼rnberg (FAU)
        caption: October 2020 - May 2024
        sub_title: M.Sc. Computational and Applied Mathematics
        link: fau.de
        quote: >
           "Founded in 1743, FAU is one of Germanyâ€™s leading research universities, ranked #1 worldwide for innovation in the Times Higher Education Impact Rankings."
        description: | # this will include new lines to allow paragraphs
          My studies in computational and applied mathematics gave me the chance to refine my skills in data analysis, mathematical modeling, and machine learning. I focused on applying these techniques to real-world problems, with a particular emphasis on image processing and creating innovative solutions driven by data.\\
          ğŸ“Œ **Thesis topics:**
          - Hypegraph *p*-Laplace Operators for Image Denoising (M.Sc., 2023) [[GitHub](https://github.com/kslukin/FAU_Master_Thesis)]

          **Key courses:**
          - Mathematical Data Science 
          - Control, machine learning and numerics
          - Modeling, simulation and optimization (Practical Course)
          - Mathematical Image Processing
          - Programming techniques for supercomputers 
          

      
      - layout: left
        title: ğŸ“ Moscow State University of Civil Engineering (MSUCE)
        caption: September 2015 - June 2021
        sub_title: M.Sc. Applied Mechanics and B.Sc. Applied Mathematics
        link: mgsu.ru
        quote: >
           "For over 100 years, the university has combined tradition and innovation to educate civil engineers who shape the built environment."
        description: | # this will include new lines to allow paragraphs
          My time at MSUCE was where it all started - long nights with math models, unexpected breakthroughs, and the first real spark of curiosity about how data reflects the world around us. I began by analyzing economic trends in construction, and a few years later found myself diving into the strange beauty of stock market fractals. These years gave me not just two degrees, but a real passion for patterns, complexity, and making sense of the numbers behind the scenes.\\
          ğŸ“Œ **Thesis topics:**
          - Statistical Analysis of Stock Market Fractal Nature (M.Sc., 2021)
          - Statistical Analysis of Defined Economic Indices of Construction Industry Functioning (B.Sc., 2019)
          
          **Key courses:**
          - Mathematical Analysis and Differential Equations
          - Probability Theory, Mathematical Statistics and Theory of Random Processes
          - Numerical Methods, Mathematical Simulation and Optimization Methods
          - Data Bases and Intelligent Systems
          - Programming in C++ and MATLAB
     
  - title: ğŸ“š Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      Hypergraph *p* - Laplacians and Scale Spaces. A.Fazeny, D.Tenbrinck, K.Lukin and M.Burger.
      - Journal Math Imaging Vision 66, 529â€“549 (2024). [[link](https://doi.org/10.1007/s10851-024-01183-0)]
      - Journal Scale Space and Variational Methods in Computer Vision, 677â€“690 (2023). [[link](http://dx.doi.org/10.1007/978-3-031-31975-4_52)]
  
  - title: ğŸš€ Courses 
    layout: text
    content: | # this will include new lines to allow paragraphs
      90

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in math and Python programming some of my other interests and hobbies are:
      - Yoga ğŸ§˜â€â™€ï¸
      - Baking ğŸ°
      - Painting by numbers ğŸ–¼ï¸
      


  
    

     ## Look at this cool image  
     ## ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
